name: CliffPhys
channels:
  - anaconda
  - pytorch
  - nvidia
  - defaults
dependencies:
    - scipy=1.11.4
    - pytorch=2.2.1
    - pytorch-cuda=11.7
    - torchaudio=2.2.1
    - torchvision=0.17.1
    - matplotlib=3.8.0
    - pandas=2.1.1
    - seaborn=0.12.2
    - pip:
       - opencv-python==4.7.0.72
       - prettytable==3.10.0
       - tqdm==4.66.2